services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: avito-server
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      OLLAMA_URL: http://host.docker.internal:11434/api/generate
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: avito-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8080
    depends_on:
      - server
